#!/bin/bash
# ANALYST AGENT — Monitor strategy_pool performance, generate reports, suggest refinements
# Runs every 1h per QUANT_TEAM_ARCHITECTURE.md
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
OUTPUT="/home/frank/obsidian/quant-team/research/analyst/${DATE}-performance-review.md"
mkdir -p "$(dirname "$OUTPUT")"

docker exec -e PGPASSWORD=*** sycodetrading-supabase-db psql -h localhost -U postgres -d postgres -t -A -F'|' <<'SQL' > /tmp/analyst_results.txt
SELECT 
  name,
  tier,
  status,
  total_trades,
  win_rate,
  avg_pnl,
  sharpe_ratio,
  max_drawdown,
  creator
FROM strategy_pool 
ORDER BY tier DESC, sharpe_ratio DESC, avg_pnl DESC;
SQL

cat > "$OUTPUT" << EOF
# Analyst Performance Review — ${DATE} ${TIME}

## Strategy Pool Snapshot

| Name | Tier | Status | Trades | Win% | AvgPnL | Sharpe | MaxDD | Creator |
|------|------|--------|--------|------|--------|--------|-------|---------|
EOF

while IFS='|' read -r name tier status trades win avg sharpe maxdd creator; do
  echo "| $name | $tier | $status | $trades | $win | $avg | $sharpe | $maxdd | $creator |" >> "$OUTPUT"
done < /tmp/analyst_results.txt

cat >> "$OUTPUT" << EOF

## Key Observations
- All strategies currently in paper tier with 0 trades (awaiting live signals or backtests).
- Top contenders from recent pattern mining: Pattern_VolumeRatio_15m_Medium_LONG, Pattern_MultiIndicator_1d_Extreme_SHORT, etc.
- Next: Promote contenders to live once 30+ trades logged via trader_agent.

## Recommendations
- Run strategist backtests on top 5 patterns using n8n workflows.
- Monitor signal_journeys for early performance data.
- Analyst cron will re-run hourly and update this report.

Auto-generated by Analyst Agent — $(date)
Written to: $OUTPUT
EOF

echo "Analyst report written to: $OUTPUT"
echo "Strategy pool review complete."